{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.howxu.chocolate_gradle",
    "module": "chocolate_gradle",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "chocolate_gradle-1.0.jar",
          "url": "chocolate_gradle-1.0.jar",
          "size": 12182,
          "sha512": "0d1256ef31ac4596ae8199e8c471a1610da4681296679fa3fef0b0556b456ccc3f1717225c9d702875332298f52f1db46b6fe72585c242bb84faf2ce2d9db2dd",
          "sha256": "8ddb8f4ced9f32e22788be13d28488bf377b96cc55a7ece87cae6ed372bb2f3f",
          "sha1": "cd31156378b9661f492511dc06b4e3e0bd71c120",
          "md5": "6a888745ca6606cfc3a2b97794f57c40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "chocolate_gradle-1.0.jar",
          "url": "chocolate_gradle-1.0.jar",
          "size": 12182,
          "sha512": "0d1256ef31ac4596ae8199e8c471a1610da4681296679fa3fef0b0556b456ccc3f1717225c9d702875332298f52f1db46b6fe72585c242bb84faf2ce2d9db2dd",
          "sha256": "8ddb8f4ced9f32e22788be13d28488bf377b96cc55a7ece87cae6ed372bb2f3f",
          "sha1": "cd31156378b9661f492511dc06b4e3e0bd71c120",
          "md5": "6a888745ca6606cfc3a2b97794f57c40"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chocolate_gradle-1.0-javadoc.jar",
          "url": "chocolate_gradle-1.0-javadoc.jar",
          "size": 48819,
          "sha512": "d28b91a047bd5ca0f0cd711214c3cdf7d3b50881972afa4239221b5a46c8cbe50bc52163cd79f018111fb3b54f4937743dd12202f12356bf1179edf57b069bc5",
          "sha256": "309cffa50e026ec9d095a97eea8e8c948b7b29ef52832ac064675eb7262a240d",
          "sha1": "3da2dd22b8e8595d801c007adfec9033a0a76265",
          "md5": "dc7203ed9b9e249db22fbe4cfb08c57d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chocolate_gradle-1.0-sources.jar",
          "url": "chocolate_gradle-1.0-sources.jar",
          "size": 7515,
          "sha512": "8f8fd89bc936893f464259ec415fb4402ce7cf534f107083a1ef8ac66410e637255bed159957b9dbee31e768c84f838f39f710960402bcaf2a91d826e048709c",
          "sha256": "3d7a3d6d124363286953b26dd55f251216160554dd4d17030734840c489e0d9e",
          "sha1": "858d9e1349ac65372628ca9dd387dc95d56e9312",
          "md5": "b40428acc810ed9475e4a58901a904e2"
        }
      ]
    }
  ]
}
