{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.howxu.chocolate_gradle",
    "module": "chocolate_gradle",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "chocolate_gradle-1.0.jar",
          "url": "chocolate_gradle-1.0.jar",
          "size": 1870,
          "sha512": "ad07b7612fc5bd2c224b03cbe0247ab34b3aa35ac9d1a510f9b13d8a3d5a2938bbffde9ef2e620e35b2855f2e66c1e34cb47c3b9bc2cb4131f214958adbfea09",
          "sha256": "412213f986e533383c45d6a29888549474b5428b6b1be94da25d89b68cd6a0de",
          "sha1": "44e4f1ee3bc5ba6f2f709502076272c010b9359e",
          "md5": "16337a1463be500d22696c854a9f6caf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chocolate_gradle-1.0.jar",
          "url": "chocolate_gradle-1.0.jar",
          "size": 1870,
          "sha512": "ad07b7612fc5bd2c224b03cbe0247ab34b3aa35ac9d1a510f9b13d8a3d5a2938bbffde9ef2e620e35b2855f2e66c1e34cb47c3b9bc2cb4131f214958adbfea09",
          "sha256": "412213f986e533383c45d6a29888549474b5428b6b1be94da25d89b68cd6a0de",
          "sha1": "44e4f1ee3bc5ba6f2f709502076272c010b9359e",
          "md5": "16337a1463be500d22696c854a9f6caf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chocolate_gradle-1.0-javadoc.jar",
          "url": "chocolate_gradle-1.0-javadoc.jar",
          "size": 19326,
          "sha512": "8f9b4536d0c608fbda5b3b25ef8d6f0d54deca3d5679f1a7bb4f7255a9e75d8b2e03e4ad455bbc5c32ba8a16e8776b67b2166d68794211a7369bf9faaed2770f",
          "sha256": "a416b3e9a91ca4567208c403f33dc533df0da2ea5e7a9858814cc5f1e7d35084",
          "sha1": "37d0bf6323f8205efb8be035085a006d7ab245b9",
          "md5": "17ea0a420c14b7943ba661a183020c42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chocolate_gradle-1.0-sources.jar",
          "url": "chocolate_gradle-1.0-sources.jar",
          "size": 1283,
          "sha512": "3ce9100f9ad66d24c041d1cdd51d2505d45be0cd9a7a0be852b9e60a6bb7538a9cf66e2ad35ffe7a32866e6f62622d8b72522e6ed0d6f9a595a83dd08cc6ddac",
          "sha256": "96336d25a389ea2899a8f6b915afabe3cbdcbb0b33584b0250f3a4f30a8034c4",
          "sha1": "1d9590c71d55cb14d0b0a3950e3663290e4b2248",
          "md5": "4f1165323a57ec2c9917fe51aca47754"
        }
      ]
    }
  ]
}
